FROM python:3.7-alpine

ARG CONSUMER_KEY
ARG CONSUMER_SECRET
ARG ACCESS_TOKEN
ARG ACCESS_TOKEN_SECRET

ENV CONSUMER_KEY ${CONSUMER_KEY}
ENV CONSUMER_SECRET ${CONSUMER_SECRET}
ENV ACCESS_TOKEN ${ACCESS_TOKEN}
ENV ACCESS_TOKEN_SECRET ${ACCESS_TOKEN_SECRET}

COPY bots/config.py /bots/
COPY bots/favretweet.py /bots/
COPY requirements.txt /tmp
RUN pip3 install -r /tmp/requirements.txt

WORKDIR /bots
CMD ["python3", "favretweet.py"]